name: english_learner
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  bloc_concurrency: ^0.2.4
  equatable: ^2.0.5
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  cloud_firestore: ^4.15.8
  hive: ^2.2.3
  flutter_tts: ^3.8.5
  sqflite: ^2.3.2
  dio: ^5.4.1
  fluttertoast: ^8.2.4
  translator: ^1.0.0
  flutter_local_notifications: ^15.1.1
  flutter_timezone: ^1.0.7
  rxdart: ^0.27.7
  workmanager: ^0.5.2
  permission_handler: ^11.3.0
  flutter_card_swiper: ^7.0.0
  flippy: ^0.1.1
  animated_notch_bottom_bar: ^1.0.0


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/dictionary.json
    - assets/notification.wav
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
