// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm9raYXGLDWSKGzAIpOcWgPEMA5KZLcAQ',
    appId: '1:593616150940:web:4a8af92c2a2d6a9eae2859',
    messagingSenderId: '593616150940',
    projectId: 'vocabhunter-de98d',
    authDomain: 'vocabhunter-de98d.firebaseapp.com',
    storageBucket: 'vocabhunter-de98d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuKmxoDePwOsYorGkBnZEnu05zIybXMDk',
    appId: '1:593616150940:android:d415c40a5f7278e0ae2859',
    messagingSenderId: '593616150940',
    projectId: 'vocabhunter-de98d',
    storageBucket: 'vocabhunter-de98d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYoTm9RxarKSaKlEwLlDLeCvWaDs5V69g',
    appId: '1:593616150940:ios:f0be520104919f77ae2859',
    messagingSenderId: '593616150940',
    projectId: 'vocabhunter-de98d',
    storageBucket: 'vocabhunter-de98d.appspot.com',
    iosBundleId: 'com.example.englishLearner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYoTm9RxarKSaKlEwLlDLeCvWaDs5V69g',
    appId: '1:593616150940:ios:62aced603b653267ae2859',
    messagingSenderId: '593616150940',
    projectId: 'vocabhunter-de98d',
    storageBucket: 'vocabhunter-de98d.appspot.com',
    iosBundleId: 'com.example.englishLearner.RunnerTests',
  );
}
