// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpdam2Qzr9LQdcxr38Jv2wFk9QoPMVmhc',
    appId: '1:676058831524:web:386aadc6f113b65d9c2431',
    messagingSenderId: '676058831524',
    projectId: 'myenglishlearner-22a85',
    authDomain: 'myenglishlearner-22a85.firebaseapp.com',
    storageBucket: 'myenglishlearner-22a85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDICD7rMQf1WpfTb0bgUznYtO_FJw662nI',
    appId: '1:676058831524:android:5d01fdb5384acaae9c2431',
    messagingSenderId: '676058831524',
    projectId: 'myenglishlearner-22a85',
    storageBucket: 'myenglishlearner-22a85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKaKdHkm1Dad6Ww4IMbbnevIV0qDqDDxw',
    appId: '1:676058831524:ios:e7d307797e6a237e9c2431',
    messagingSenderId: '676058831524',
    projectId: 'myenglishlearner-22a85',
    storageBucket: 'myenglishlearner-22a85.appspot.com',
    iosBundleId: 'com.example.englishLearner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKaKdHkm1Dad6Ww4IMbbnevIV0qDqDDxw',
    appId: '1:676058831524:ios:819c4f8e2c51377b9c2431',
    messagingSenderId: '676058831524',
    projectId: 'myenglishlearner-22a85',
    storageBucket: 'myenglishlearner-22a85.appspot.com',
    iosBundleId: 'com.example.englishLearner.RunnerTests',
  );
}
